path:
    train_path: ./raw_train.csv
    dev_path: ./raw_val.csv # 수정 필요
    predict_path: ./raw_test.csv

# TODO
exp:
    exp_name : base-klue-roberta-large # 변경 해야함!! 실험 이름
    project_name : ik_klue-roberta_exp # 변경 해야함!! 실험 공간 ex) Moongi_exp

data:
    aug_option : None
    mode : False
# TODO    
model:
    model_name: klue/roberta-large
    type : base
    type2 : None 
train:
    loss_name : 'focal'
    gpus: 1
    batch_size: 32
    max_epoch: 30
    learning_rate: 5e-5
    logging_step: 1
    save_total_limit : 3 # number of total save model.
    save_steps : 500 # model saving step.
    warmup_steps : 500 # number of warmup steps for learning rate scheduler
    weight_decay : 0.01 # strength of weight decay
    logging_steps : 100  # log saving step.
    eval_steps : 500 # evaluation step
    scheduler : 'linear' # linear OR cosine OR steplr
    metric_for_best_model : 'micro f1 score'
    patience : 10

test:
    model_dir : ./results/base-klue-roberta-large/checkpoint-22500/pytorch_model.bin
    prediction : ./predict/roberta-large.csv
